version: '3.9'

services:
  certbot:
    container_name: certbot
    build:
      dockerfile: Dockerfile
      context: ./certbot
    depends_on:
      - nginx
    image: certbot/certbot:v.1.0.3
    # command: certonly --webroot --webroot-path=/var/www/certbot --email kheshtinco@gmail.com --agree-tos --no-eff-email --keep --expand --cert-name kheshtin.ir -d test.kheshtin.ir -d orchard.kheshtin.ir -d kheshtin.ir
    volumes:
      - /root/certbot/www/:/var/www/certbot/:rw
      - /root/certbot/conf/:/etc/letsencrypt/:rw

  nginx:
    container_name: nginx    
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx-cert
    image: nginx:v1.0.5
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-cert/conf/:/etc/nginx/conf.d/:ro
      - /root/certbot/www/:/var/www/certbot/:ro
      - /root/certbot/conf/:/etc/nginx/ssl/:ro
    

 