name: Deploy

on: [push]

jobs:
  simpleExample:
    runs-on: self-hosted
    steps:
    # checkout branch
    - uses: actions/checkout@master
    - name: Docker version
      run: docker --version










