name: Deploy

on: [push]

jobs:
  simpleExample:
    runs-on: self-hosted
    steps:
    # checkout branch
    - uses: actions/checkout@master
    - name: Docker version
      run: docker --version
    - name: Docker Compose down
      run: docker-compose -f docker-compose.prod.yaml down
    - name: Docker Compose up
      run: docker-compose -f docker-compose.prod.yaml up -d










