name: Deploy

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: self-hosted
  deploy:
    runs-on: self-hosted

steps:
  - name: Checkout code

uses: actions/checkout@v2
  - name: Setup SSH

  
run: |
  command -v ssh-agent >/dev/null || ( sudo apt-get update && sudo apt-get install -y openssh-client )
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  ssh-keyscan ${{ secrets.REPO_IPADDRESS }} >> ~/.ssh/known_hosts
  chmod 644 ~/.ssh/known_hosts
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  - name: Log in to Docker Hub

run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  - name: Check Docker version

run: docker --version
  - name: Docker Compose down

run: docker-compose -f docker-compose.prod.yaml down
  - name: Docker Compose up

run: docker-compose -f docker-compose.prod.yaml up -d
